# Generated by Django 4.0.6 on 2022-07-27 17:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Facilidades',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateField(auto_now_add=True)),
                ('atualizado_em', models.DateField(auto_now_add=True)),
                ('facilidade_nome', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateField(auto_now_add=True)),
                ('atualizado_em', models.DateField(auto_now_add=True)),
                ('hotel_nome', models.CharField(max_length=100)),
                ('hotel_preco', models.IntegerField()),
                ('descricao', models.TextField()),
                ('qtd_quartos', models.IntegerField(default=10)),
                ('facilidades', models.ManyToManyField(to='home.facilidades')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HotelReserva',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateField(auto_now_add=True)),
                ('atualizado_em', models.DateField(auto_now_add=True)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('tipo_de_reserva', models.CharField(choices=[('Pre Pagamento', 'Pre Pagamento'), ('Pos Pagamento', 'Pos Pagamento')], max_length=100)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotel_reserva', to='home.hotel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_reserva', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HotelImagem',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateField(auto_now_add=True)),
                ('atualizado_em', models.DateField(auto_now_add=True)),
                ('imagem', models.ImageField(upload_to='hotels')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='home.hotel')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
